-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_db_insert_sort_function_insert_sort_top_unsigned_int_unsigned_int_4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    din_strm_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    din_strm_V_empty_n : IN STD_LOGIC;
    din_strm_V_read : OUT STD_LOGIC;
    kin_strm_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    kin_strm_V_empty_n : IN STD_LOGIC;
    kin_strm_V_read : OUT STD_LOGIC;
    strm_in_end_V_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    strm_in_end_V_empty_n : IN STD_LOGIC;
    strm_in_end_V_read : OUT STD_LOGIC;
    dout_strm_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dout_strm_V_full_n : IN STD_LOGIC;
    dout_strm_V_write : OUT STD_LOGIC;
    kout_strm_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    kout_strm_V_full_n : IN STD_LOGIC;
    kout_strm_V_write : OUT STD_LOGIC;
    strm_out_end_V_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    strm_out_end_V_full_n : IN STD_LOGIC;
    strm_out_end_V_write : OUT STD_LOGIC;
    sign : IN STD_LOGIC );
end;


architecture behav of hls_db_insert_sort_function_insert_sort_top_unsigned_int_unsigned_int_4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000101";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv16_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000011";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal din_strm_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal and_ln58_reg_797 : STD_LOGIC_VECTOR (0 downto 0);
    signal end_2_reg_159 : STD_LOGIC_VECTOR (0 downto 0);
    signal kin_strm_V_blk_n : STD_LOGIC;
    signal strm_in_end_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal and_ln58_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_end_2_phi_fu_162_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_strm_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal array_full_reg_194 : STD_LOGIC_VECTOR (0 downto 0);
    signal kout_strm_V_blk_n : STD_LOGIC;
    signal strm_out_end_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_predicate_op35_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op40_read_state3 : BOOLEAN;
    signal ap_predicate_op41_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal residual_count_reg_169 : STD_LOGIC_VECTOR (15 downto 0);
    signal end_1_reg_181 : STD_LOGIC_VECTOR (0 downto 0);
    signal inserting_id_reg_206 : STD_LOGIC_VECTOR (15 downto 0);
    signal lnot_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lnot_reg_790 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln58_reg_797_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_reg_801 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_1_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_1_reg_806 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_2_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_2_reg_811 : STD_LOGIC_VECTOR (0 downto 0);
    signal array_full_1_fu_307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal array_full_1_reg_816 : STD_LOGIC_VECTOR (0 downto 0);
    signal inserting_id_2_fu_313_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal residual_count_1_fu_321_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_condition_pp0_exit_iter1_state3 : STD_LOGIC;
    signal ap_phi_mux_residual_count_phi_fu_173_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_end_1_reg_181 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_array_full_phi_fu_198_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_68 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln97_4_fu_659_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_11_fu_72 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln97_3_fu_651_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_temp_1_fu_76 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln98_5_fu_611_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_temp_fu_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln98_1_fu_513_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_dtemp_fu_84 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln98_fu_489_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_dtemp_1_fu_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln98_4_fu_587_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_12_fu_92 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln97_2_fu_643_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_13_fu_96 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln97_1_fu_635_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_14_fu_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln97_fu_627_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_dtemp_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_temp_fu_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal lnot_fu_217_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_245_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_1_fu_267_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln124_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_15_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal inserting_id_1_fu_295_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal residual_count_2_fu_283_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln74_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln76_fu_370_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln76_fu_370_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_1_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln76_1_fu_387_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln76_1_fu_387_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_2_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln76_2_fu_404_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln76_2_fu_404_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln73_2_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln73_1_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln98_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln98_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln103_fu_437_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln87_fu_415_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln97_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln73_fu_473_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln97_5_fu_481_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln103_1_fu_445_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln87_1_fu_423_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_1_fu_497_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln97_6_fu_505_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln73_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_dtemp_4_fu_465_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_temp_4_fu_521_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln98_1_fu_551_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln98_1_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln103_2_fu_535_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln97_1_fu_529_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln73_2_fu_571_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln97_7_fu_579_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln103_3_fu_543_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_3_fu_595_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln97_8_fu_603_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln98_3_fu_563_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln98_6_fu_619_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_192 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (strm_in_end_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter1_state3)) or (not(((ap_start = ap_const_logic_0) or (strm_in_end_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter1_state3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((not(((ap_start = ap_const_logic_0) or (strm_in_end_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    array_full_reg_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_lv1_0 = and_ln58_reg_797_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                array_full_reg_194 <= array_full_1_reg_816;
            elsif ((not(((ap_start = ap_const_logic_0) or (strm_in_end_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                array_full_reg_194 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    end_1_reg_181_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_192)) then
                if (((ap_phi_mux_end_2_phi_fu_162_p4 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln58_fu_229_p2))) then 
                    end_1_reg_181 <= ap_const_lv1_1;
                elsif (((ap_phi_mux_end_2_phi_fu_162_p4 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln58_fu_229_p2))) then 
                    end_1_reg_181 <= strm_in_end_V_dout;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    end_1_reg_181 <= ap_phi_reg_pp0_iter0_end_1_reg_181;
                end if;
            end if; 
        end if;
    end process;

    end_2_reg_159_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = and_ln58_reg_797) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                end_2_reg_159 <= end_1_reg_181;
            elsif ((not(((ap_start = ap_const_logic_0) or (strm_in_end_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                end_2_reg_159 <= strm_in_end_V_dout;
            end if; 
        end if;
    end process;

    inserting_id_reg_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = and_ln58_reg_797) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                inserting_id_reg_206 <= inserting_id_2_fu_313_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (strm_in_end_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                inserting_id_reg_206 <= ap_const_lv16_1;
            end if; 
        end if;
    end process;

    residual_count_reg_169_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = and_ln58_reg_797) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                residual_count_reg_169 <= residual_count_1_fu_321_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (strm_in_end_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                residual_count_reg_169 <= ap_const_lv16_5;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln58_reg_797 <= and_ln58_fu_229_p2;
                and_ln58_reg_797_pp0_iter1_reg <= and_ln58_reg_797;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = and_ln58_reg_797) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                array_full_1_reg_816 <= array_full_1_fu_307_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                empty_11_fu_72 <= select_ln97_3_fu_651_p3;
                empty_12_fu_92 <= select_ln97_2_fu_643_p3;
                empty_13_fu_96 <= select_ln97_1_fu_635_p3;
                empty_14_fu_100 <= select_ln97_fu_627_p3;
                empty_fu_68 <= select_ln97_4_fu_659_p3;
                in_dtemp_1_fu_88 <= select_ln98_4_fu_587_p3;
                in_temp_1_fu_76 <= select_ln98_5_fu_611_p3;
                out_dtemp_fu_84 <= select_ln98_fu_489_p3;
                out_temp_fu_80 <= select_ln98_1_fu_513_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = and_ln58_reg_797) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln73_1_reg_806 <= icmp_ln73_1_fu_261_p2;
                icmp_ln73_2_reg_811 <= icmp_ln73_2_fu_277_p2;
                icmp_ln73_reg_801 <= icmp_ln73_fu_255_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((end_2_reg_159 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln58_reg_797) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                in_dtemp_fu_104 <= din_strm_V_dout;
                in_temp_fu_108 <= kin_strm_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                lnot_reg_790 <= lnot_fu_217_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, strm_in_end_V_empty_n, strm_out_end_V_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0, ap_CS_fsm_state5, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (strm_in_end_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state5 => 
                if (((strm_out_end_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    and_ln58_fu_229_p2 <= (icmp_ln58_fu_223_p2 and ap_phi_mux_end_2_phi_fu_162_p4);
    and_ln98_1_fu_557_p2 <= (xor_ln98_1_fu_551_p2 and or_ln73_1_fu_393_p2);
    and_ln98_fu_459_p2 <= (xor_ln98_fu_453_p2 and or_ln73_2_fu_410_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state5 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(din_strm_V_empty_n, kin_strm_V_empty_n, strm_in_end_V_empty_n, dout_strm_V_full_n, kout_strm_V_full_n, strm_out_end_V_full_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, array_full_reg_194, ap_predicate_op35_read_state2, ap_predicate_op40_read_state3, ap_predicate_op41_read_state3)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((array_full_reg_194 = ap_const_lv1_1) and (strm_out_end_V_full_n = ap_const_logic_0)) or ((array_full_reg_194 = ap_const_lv1_1) and (dout_strm_V_full_n = ap_const_logic_0)) or ((array_full_reg_194 = ap_const_lv1_1) and (kout_strm_V_full_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (strm_in_end_V_empty_n = ap_const_logic_0) and (ap_predicate_op35_read_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((din_strm_V_empty_n = ap_const_logic_0) and (ap_predicate_op41_read_state3 = ap_const_boolean_1)) or ((kin_strm_V_empty_n = ap_const_logic_0) and (ap_predicate_op40_read_state3 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(din_strm_V_empty_n, kin_strm_V_empty_n, strm_in_end_V_empty_n, dout_strm_V_full_n, kout_strm_V_full_n, strm_out_end_V_full_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, array_full_reg_194, ap_predicate_op35_read_state2, ap_predicate_op40_read_state3, ap_predicate_op41_read_state3)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((array_full_reg_194 = ap_const_lv1_1) and (strm_out_end_V_full_n = ap_const_logic_0)) or ((array_full_reg_194 = ap_const_lv1_1) and (dout_strm_V_full_n = ap_const_logic_0)) or ((array_full_reg_194 = ap_const_lv1_1) and (kout_strm_V_full_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (strm_in_end_V_empty_n = ap_const_logic_0) and (ap_predicate_op35_read_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((din_strm_V_empty_n = ap_const_logic_0) and (ap_predicate_op41_read_state3 = ap_const_boolean_1)) or ((kin_strm_V_empty_n = ap_const_logic_0) and (ap_predicate_op40_read_state3 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(din_strm_V_empty_n, kin_strm_V_empty_n, strm_in_end_V_empty_n, dout_strm_V_full_n, kout_strm_V_full_n, strm_out_end_V_full_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, array_full_reg_194, ap_predicate_op35_read_state2, ap_predicate_op40_read_state3, ap_predicate_op41_read_state3)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((array_full_reg_194 = ap_const_lv1_1) and (strm_out_end_V_full_n = ap_const_logic_0)) or ((array_full_reg_194 = ap_const_lv1_1) and (dout_strm_V_full_n = ap_const_logic_0)) or ((array_full_reg_194 = ap_const_lv1_1) and (kout_strm_V_full_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (strm_in_end_V_empty_n = ap_const_logic_0) and (ap_predicate_op35_read_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((din_strm_V_empty_n = ap_const_logic_0) and (ap_predicate_op41_read_state3 = ap_const_boolean_1)) or ((kin_strm_V_empty_n = ap_const_logic_0) and (ap_predicate_op40_read_state3 = ap_const_boolean_1)))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, strm_in_end_V_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (strm_in_end_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(strm_in_end_V_empty_n, ap_predicate_op35_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter0 <= ((strm_in_end_V_empty_n = ap_const_logic_0) and (ap_predicate_op35_read_state2 = ap_const_boolean_1));
    end process;


    ap_block_state3_pp0_stage0_iter1_assign_proc : process(din_strm_V_empty_n, kin_strm_V_empty_n, ap_predicate_op40_read_state3, ap_predicate_op41_read_state3)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (((din_strm_V_empty_n = ap_const_logic_0) and (ap_predicate_op41_read_state3 = ap_const_boolean_1)) or ((kin_strm_V_empty_n = ap_const_logic_0) and (ap_predicate_op40_read_state3 = ap_const_boolean_1)));
    end process;


    ap_block_state4_pp0_stage0_iter2_assign_proc : process(dout_strm_V_full_n, kout_strm_V_full_n, strm_out_end_V_full_n, array_full_reg_194)
    begin
                ap_block_state4_pp0_stage0_iter2 <= (((array_full_reg_194 = ap_const_lv1_1) and (strm_out_end_V_full_n = ap_const_logic_0)) or ((array_full_reg_194 = ap_const_lv1_1) and (dout_strm_V_full_n = ap_const_logic_0)) or ((array_full_reg_194 = ap_const_lv1_1) and (kout_strm_V_full_n = ap_const_logic_0)));
    end process;


    ap_condition_192_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_192 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_pp0_exit_iter1_state3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_condition_pp0_exit_iter1_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter1_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(ap_CS_fsm_pp0_stage0, and_ln58_fu_229_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_lv1_1 = and_ln58_fu_229_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, strm_out_end_V_full_n, ap_CS_fsm_state5)
    begin
        if ((((strm_out_end_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_array_full_phi_fu_198_p4_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, array_full_reg_194, and_ln58_reg_797_pp0_iter1_reg, array_full_1_reg_816)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_lv1_0 = and_ln58_reg_797_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_array_full_phi_fu_198_p4 <= array_full_1_reg_816;
        else 
            ap_phi_mux_array_full_phi_fu_198_p4 <= array_full_reg_194;
        end if; 
    end process;


    ap_phi_mux_end_2_phi_fu_162_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, and_ln58_reg_797, end_2_reg_159, end_1_reg_181)
    begin
        if (((ap_const_lv1_0 = and_ln58_reg_797) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_end_2_phi_fu_162_p4 <= end_1_reg_181;
        else 
            ap_phi_mux_end_2_phi_fu_162_p4 <= end_2_reg_159;
        end if; 
    end process;


    ap_phi_mux_residual_count_phi_fu_173_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, and_ln58_reg_797, residual_count_reg_169, residual_count_1_fu_321_p3)
    begin
        if (((ap_const_lv1_0 = and_ln58_reg_797) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_residual_count_phi_fu_173_p4 <= residual_count_1_fu_321_p3;
        else 
            ap_phi_mux_residual_count_phi_fu_173_p4 <= residual_count_reg_169;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_end_1_reg_181 <= "X";

    ap_predicate_op35_read_state2_assign_proc : process(and_ln58_fu_229_p2, ap_phi_mux_end_2_phi_fu_162_p4)
    begin
                ap_predicate_op35_read_state2 <= ((ap_phi_mux_end_2_phi_fu_162_p4 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln58_fu_229_p2));
    end process;


    ap_predicate_op40_read_state3_assign_proc : process(and_ln58_reg_797, end_2_reg_159)
    begin
                ap_predicate_op40_read_state3 <= ((end_2_reg_159 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln58_reg_797));
    end process;


    ap_predicate_op41_read_state3_assign_proc : process(and_ln58_reg_797, end_2_reg_159)
    begin
                ap_predicate_op41_read_state3 <= ((end_2_reg_159 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln58_reg_797));
    end process;


    ap_ready_assign_proc : process(strm_out_end_V_full_n, ap_CS_fsm_state5)
    begin
        if (((strm_out_end_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    array_full_1_fu_307_p2 <= (empty_15_fu_301_p2 or ap_phi_mux_array_full_phi_fu_198_p4);

    din_strm_V_blk_n_assign_proc : process(din_strm_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, and_ln58_reg_797, end_2_reg_159)
    begin
        if (((end_2_reg_159 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln58_reg_797) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_strm_V_blk_n <= din_strm_V_empty_n;
        else 
            din_strm_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_strm_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op41_read_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op41_read_state3 = ap_const_boolean_1))) then 
            din_strm_V_read <= ap_const_logic_1;
        else 
            din_strm_V_read <= ap_const_logic_0;
        end if; 
    end process;


    dout_strm_V_blk_n_assign_proc : process(dout_strm_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, array_full_reg_194)
    begin
        if (((array_full_reg_194 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            dout_strm_V_blk_n <= dout_strm_V_full_n;
        else 
            dout_strm_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dout_strm_V_din <= out_dtemp_fu_84;

    dout_strm_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, array_full_reg_194, ap_block_pp0_stage0_11001)
    begin
        if (((array_full_reg_194 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dout_strm_V_write <= ap_const_logic_1;
        else 
            dout_strm_V_write <= ap_const_logic_0;
        end if; 
    end process;

    empty_15_fu_301_p2 <= (icmp_ln124_fu_289_p2 or end_1_reg_181);
    icmp_ln124_fu_289_p2 <= "1" when (inserting_id_reg_206 = ap_const_lv16_4) else "0";
    icmp_ln58_fu_223_p2 <= "1" when (ap_phi_mux_residual_count_phi_fu_173_p4 = ap_const_lv16_0) else "0";
    icmp_ln73_1_fu_261_p2 <= "1" when (unsigned(inserting_id_reg_206) < unsigned(ap_const_lv16_3)) else "0";
    icmp_ln73_2_fu_277_p2 <= "1" when (tmp_1_fu_267_p4 = ap_const_lv14_0) else "0";
    icmp_ln73_fu_255_p2 <= "1" when (tmp_fu_245_p4 = ap_const_lv15_0) else "0";
    icmp_ln74_1_fu_381_p2 <= "1" when (unsigned(empty_11_fu_72) < unsigned(in_temp_fu_108)) else "0";
    icmp_ln74_2_fu_398_p2 <= "1" when (unsigned(in_temp_1_fu_76) < unsigned(in_temp_fu_108)) else "0";
    icmp_ln74_fu_364_p2 <= "1" when (unsigned(empty_fu_68) < unsigned(in_temp_fu_108)) else "0";
    in_dtemp_4_fu_465_p3 <= 
        in_dtemp_fu_104 when (and_ln98_fu_459_p2(0) = '1') else 
        in_dtemp_1_fu_88;
    in_temp_4_fu_521_p3 <= 
        in_temp_fu_108 when (and_ln98_fu_459_p2(0) = '1') else 
        in_temp_1_fu_76;
    inserting_id_1_fu_295_p2 <= std_logic_vector(unsigned(inserting_id_reg_206) + unsigned(ap_const_lv16_1));
    inserting_id_2_fu_313_p3 <= 
        ap_const_lv16_1 when (empty_15_fu_301_p2(0) = '1') else 
        inserting_id_1_fu_295_p2;

    kin_strm_V_blk_n_assign_proc : process(kin_strm_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, and_ln58_reg_797, end_2_reg_159)
    begin
        if (((end_2_reg_159 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln58_reg_797) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            kin_strm_V_blk_n <= kin_strm_V_empty_n;
        else 
            kin_strm_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    kin_strm_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op40_read_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op40_read_state3 = ap_const_boolean_1))) then 
            kin_strm_V_read <= ap_const_logic_1;
        else 
            kin_strm_V_read <= ap_const_logic_0;
        end if; 
    end process;


    kout_strm_V_blk_n_assign_proc : process(kout_strm_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, array_full_reg_194)
    begin
        if (((array_full_reg_194 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            kout_strm_V_blk_n <= kout_strm_V_full_n;
        else 
            kout_strm_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    kout_strm_V_din <= out_temp_fu_80;

    kout_strm_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, array_full_reg_194, ap_block_pp0_stage0_11001)
    begin
        if (((array_full_reg_194 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kout_strm_V_write <= ap_const_logic_1;
        else 
            kout_strm_V_write <= ap_const_logic_0;
        end if; 
    end process;

    lnot_fu_217_p0 <= (0=>sign, others=>'-');
    lnot_fu_217_p2 <= (lnot_fu_217_p0 xor ap_const_lv1_1);
    or_ln73_1_fu_393_p2 <= (select_ln76_1_fu_387_p3 or icmp_ln73_1_reg_806);
    or_ln73_2_fu_410_p2 <= (select_ln76_2_fu_404_p3 or icmp_ln73_2_reg_811);
    or_ln73_fu_376_p2 <= (select_ln76_fu_370_p3 or icmp_ln73_reg_801);
    or_ln97_1_fu_529_p2 <= (or_ln73_fu_376_p2 or or_ln73_1_fu_393_p2);
    or_ln97_fu_431_p2 <= (or_ln73_2_fu_410_p2 or or_ln73_1_fu_393_p2);
    residual_count_1_fu_321_p3 <= 
        residual_count_2_fu_283_p2 when (end_1_reg_181(0) = '1') else 
        residual_count_reg_169;
    residual_count_2_fu_283_p2 <= std_logic_vector(unsigned(residual_count_reg_169) + unsigned(ap_const_lv16_FFFF));
    select_ln103_1_fu_445_p3 <= 
        in_temp_1_fu_76 when (or_ln73_2_fu_410_p2(0) = '1') else 
        in_temp_fu_108;
    select_ln103_2_fu_535_p3 <= 
        empty_12_fu_92 when (or_ln73_1_fu_393_p2(0) = '1') else 
        in_dtemp_4_fu_465_p3;
    select_ln103_3_fu_543_p3 <= 
        empty_11_fu_72 when (or_ln73_1_fu_393_p2(0) = '1') else 
        in_temp_4_fu_521_p3;
    select_ln103_fu_437_p3 <= 
        in_dtemp_1_fu_88 when (or_ln73_2_fu_410_p2(0) = '1') else 
        in_dtemp_fu_104;
    select_ln73_1_fu_497_p3 <= 
        select_ln103_1_fu_445_p3 when (or_ln73_1_fu_393_p2(0) = '1') else 
        select_ln87_1_fu_423_p3;
    select_ln73_2_fu_571_p3 <= 
        select_ln103_2_fu_535_p3 when (or_ln73_fu_376_p2(0) = '1') else 
        in_dtemp_4_fu_465_p3;
    select_ln73_3_fu_595_p3 <= 
        select_ln103_3_fu_543_p3 when (or_ln73_fu_376_p2(0) = '1') else 
        in_temp_4_fu_521_p3;
    select_ln73_fu_473_p3 <= 
        select_ln103_fu_437_p3 when (or_ln73_1_fu_393_p2(0) = '1') else 
        select_ln87_fu_415_p3;
    select_ln76_1_fu_387_p1 <= (0=>sign, others=>'-');
    select_ln76_1_fu_387_p3 <= 
        select_ln76_1_fu_387_p1 when (icmp_ln74_1_fu_381_p2(0) = '1') else 
        lnot_reg_790;
    select_ln76_2_fu_404_p1 <= (0=>sign, others=>'-');
    select_ln76_2_fu_404_p3 <= 
        select_ln76_2_fu_404_p1 when (icmp_ln74_2_fu_398_p2(0) = '1') else 
        lnot_reg_790;
    select_ln76_fu_370_p1 <= (0=>sign, others=>'-');
    select_ln76_fu_370_p3 <= 
        select_ln76_fu_370_p1 when (icmp_ln74_fu_364_p2(0) = '1') else 
        lnot_reg_790;
    select_ln87_1_fu_423_p3 <= 
        out_temp_fu_80 when (or_ln73_2_fu_410_p2(0) = '1') else 
        in_temp_fu_108;
    select_ln87_fu_415_p3 <= 
        out_dtemp_fu_84 when (or_ln73_2_fu_410_p2(0) = '1') else 
        in_dtemp_fu_104;
    select_ln97_1_fu_635_p3 <= 
        in_temp_fu_108 when (or_ln73_fu_376_p2(0) = '1') else 
        empty_13_fu_96;
    select_ln97_2_fu_643_p3 <= 
        empty_14_fu_100 when (or_ln73_fu_376_p2(0) = '1') else 
        select_ln98_3_fu_563_p3;
    select_ln97_3_fu_651_p3 <= 
        empty_13_fu_96 when (or_ln73_fu_376_p2(0) = '1') else 
        select_ln98_6_fu_619_p3;
    select_ln97_4_fu_659_p3 <= 
        in_temp_fu_108 when (or_ln73_fu_376_p2(0) = '1') else 
        empty_fu_68;
    select_ln97_5_fu_481_p3 <= 
        select_ln73_fu_473_p3 when (or_ln97_fu_431_p2(0) = '1') else 
        select_ln87_fu_415_p3;
    select_ln97_6_fu_505_p3 <= 
        select_ln73_1_fu_497_p3 when (or_ln97_fu_431_p2(0) = '1') else 
        select_ln87_1_fu_423_p3;
    select_ln97_7_fu_579_p3 <= 
        select_ln73_2_fu_571_p3 when (or_ln97_1_fu_529_p2(0) = '1') else 
        in_dtemp_4_fu_465_p3;
    select_ln97_8_fu_603_p3 <= 
        select_ln73_3_fu_595_p3 when (or_ln97_1_fu_529_p2(0) = '1') else 
        in_temp_4_fu_521_p3;
    select_ln97_fu_627_p3 <= 
        in_dtemp_fu_104 when (or_ln73_fu_376_p2(0) = '1') else 
        empty_14_fu_100;
    select_ln98_1_fu_513_p3 <= 
        in_temp_1_fu_76 when (and_ln98_fu_459_p2(0) = '1') else 
        select_ln97_6_fu_505_p3;
    select_ln98_3_fu_563_p3 <= 
        in_dtemp_fu_104 when (and_ln98_1_fu_557_p2(0) = '1') else 
        empty_12_fu_92;
    select_ln98_4_fu_587_p3 <= 
        empty_12_fu_92 when (and_ln98_1_fu_557_p2(0) = '1') else 
        select_ln97_7_fu_579_p3;
    select_ln98_5_fu_611_p3 <= 
        empty_11_fu_72 when (and_ln98_1_fu_557_p2(0) = '1') else 
        select_ln97_8_fu_603_p3;
    select_ln98_6_fu_619_p3 <= 
        in_temp_fu_108 when (and_ln98_1_fu_557_p2(0) = '1') else 
        empty_11_fu_72;
    select_ln98_fu_489_p3 <= 
        in_dtemp_1_fu_88 when (and_ln98_fu_459_p2(0) = '1') else 
        select_ln97_5_fu_481_p3;

    strm_in_end_V_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, strm_in_end_V_empty_n, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter0, and_ln58_fu_229_p2, ap_phi_mux_end_2_phi_fu_162_p4)
    begin
        if ((((ap_phi_mux_end_2_phi_fu_162_p4 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_lv1_0 = and_ln58_fu_229_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            strm_in_end_V_blk_n <= strm_in_end_V_empty_n;
        else 
            strm_in_end_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    strm_in_end_V_read_assign_proc : process(ap_start, ap_CS_fsm_state1, strm_in_end_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_predicate_op35_read_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op35_read_state2 = ap_const_boolean_1)) or (not(((ap_start = ap_const_logic_0) or (strm_in_end_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            strm_in_end_V_read <= ap_const_logic_1;
        else 
            strm_in_end_V_read <= ap_const_logic_0;
        end if; 
    end process;


    strm_out_end_V_blk_n_assign_proc : process(strm_out_end_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, array_full_reg_194, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((array_full_reg_194 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            strm_out_end_V_blk_n <= strm_out_end_V_full_n;
        else 
            strm_out_end_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    strm_out_end_V_din_assign_proc : process(strm_out_end_V_full_n, ap_enable_reg_pp0_iter2, array_full_reg_194, ap_CS_fsm_state5, ap_block_pp0_stage0_01001)
    begin
        if (((strm_out_end_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            strm_out_end_V_din <= ap_const_lv1_1;
        elsif (((array_full_reg_194 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001))) then 
            strm_out_end_V_din <= ap_const_lv1_0;
        else 
            strm_out_end_V_din <= "X";
        end if; 
    end process;


    strm_out_end_V_write_assign_proc : process(strm_out_end_V_full_n, ap_enable_reg_pp0_iter2, array_full_reg_194, ap_CS_fsm_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((array_full_reg_194 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((strm_out_end_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            strm_out_end_V_write <= ap_const_logic_1;
        else 
            strm_out_end_V_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_267_p4 <= inserting_id_reg_206(15 downto 2);
    tmp_fu_245_p4 <= inserting_id_reg_206(15 downto 1);
    xor_ln98_1_fu_551_p2 <= (or_ln73_fu_376_p2 xor ap_const_lv1_1);
    xor_ln98_fu_453_p2 <= (or_ln73_1_fu_393_p2 xor ap_const_lv1_1);
end behav;
