// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sobel_adder (
        ap_ready,
        sumx,
        sumy,
        ap_return
);


output   ap_ready;
input  [7:0] sumx;
input  [7:0] sumy;
output  [8:0] ap_return;

wire   [8:0] zext_ln33_1_fu_22_p1;
wire   [8:0] zext_ln33_fu_18_p1;

assign ap_ready = 1'b1;

assign ap_return = (zext_ln33_1_fu_22_p1 + zext_ln33_fu_18_p1);

assign zext_ln33_1_fu_22_p1 = sumy;

assign zext_ln33_fu_18_p1 = sumx;

endmodule //sobel_adder
