// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sobel_crop_upper (
        ap_ready,
        in_r,
        ap_return
);


output   ap_ready;
input  [8:0] in_r;
output  [8:0] ap_return;

wire   [0:0] tmp_fu_16_p3;

assign ap_ready = 1'b1;

assign ap_return = ((tmp_fu_16_p3[0:0] == 1'b1) ? 9'd255 : in_r);

assign tmp_fu_16_p3 = in_r[32'd8];

endmodule //sobel_crop_upper
