// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sobel_crop (
        ap_ready,
        in_r,
        ap_return
);


output   ap_ready;
input  [15:0] in_r;
output  [7:0] ap_return;

wire   [7:0] tmp_4_fu_36_p4;
wire   [0:0] tmp_5_fu_52_p3;
wire   [0:0] xor_ln29_fu_60_p2;
wire   [0:0] tmp_fu_28_p3;
wire   [0:0] icmp_ln29_fu_46_p2;
wire   [0:0] or_ln29_fu_74_p2;
wire   [7:0] select_ln29_fu_66_p3;
wire   [7:0] trunc_ln25_fu_24_p1;

assign ap_ready = 1'b1;

assign ap_return = ((or_ln29_fu_74_p2[0:0] == 1'b1) ? select_ln29_fu_66_p3 : trunc_ln25_fu_24_p1);

assign icmp_ln29_fu_46_p2 = (($signed(tmp_4_fu_36_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign or_ln29_fu_74_p2 = (tmp_fu_28_p3 | icmp_ln29_fu_46_p2);

assign select_ln29_fu_66_p3 = ((xor_ln29_fu_60_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign tmp_4_fu_36_p4 = {{in_r[15:8]}};

assign tmp_5_fu_52_p3 = in_r[32'd15];

assign tmp_fu_28_p3 = in_r[32'd15];

assign trunc_ln25_fu_24_p1 = in_r[7:0];

assign xor_ln29_fu_60_p2 = (tmp_5_fu_52_p3 ^ 1'd1);

endmodule //sobel_crop
