#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("din_strm_V_dout", 32, hls_in, 0, "ap_fifo", "fifo_data", 1),
	Port_Property("din_strm_V_empty_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 1),
	Port_Property("din_strm_V_read", 1, hls_out, 0, "ap_fifo", "fifo_update", 1),
	Port_Property("kin_strm_V_dout", 32, hls_in, 1, "ap_fifo", "fifo_data", 1),
	Port_Property("kin_strm_V_empty_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 1),
	Port_Property("kin_strm_V_read", 1, hls_out, 1, "ap_fifo", "fifo_update", 1),
	Port_Property("strm_in_end_V_dout", 1, hls_in, 2, "ap_fifo", "fifo_data", 1),
	Port_Property("strm_in_end_V_empty_n", 1, hls_in, 2, "ap_fifo", "fifo_status", 1),
	Port_Property("strm_in_end_V_read", 1, hls_out, 2, "ap_fifo", "fifo_update", 1),
	Port_Property("dout_strm_V_din", 32, hls_out, 3, "ap_fifo", "fifo_data", 1),
	Port_Property("dout_strm_V_full_n", 1, hls_in, 3, "ap_fifo", "fifo_status", 1),
	Port_Property("dout_strm_V_write", 1, hls_out, 3, "ap_fifo", "fifo_update", 1),
	Port_Property("kout_strm_V_din", 32, hls_out, 4, "ap_fifo", "fifo_data", 1),
	Port_Property("kout_strm_V_full_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 1),
	Port_Property("kout_strm_V_write", 1, hls_out, 4, "ap_fifo", "fifo_update", 1),
	Port_Property("strm_out_end_V_din", 1, hls_out, 5, "ap_fifo", "fifo_data", 1),
	Port_Property("strm_out_end_V_full_n", 1, hls_in, 5, "ap_fifo", "fifo_status", 1),
	Port_Property("strm_out_end_V_write", 1, hls_out, 5, "ap_fifo", "fifo_update", 1),
	Port_Property("sign", 1, hls_in, 6, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "hls_db_insert_sort_function";
